name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version check
        run: |
          package_json_version=$(node -e 'console.log(require("./package.json").version)')
          if [ "v$package_json_version" != $GITHUB_REF_NAME ]; then
            echo "Version in package.json (v$package_json_version) does not match the tag ($GITHUB_REF_NAME)"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          major=$(node -e 'console.log(require("./package.json").version.split(".")[0])')
          latest_major=$(npm view "$(node -e 'console.log(require("./package.json").name)')" version | cut -d. -f1)
          if [ "$major" -ge "$latest_major" ]; then
            npm publish --access=public
          else
            npm publish --access=public --tag "v$major"
          fi
